onerror {resume}
quietly virtual function -install /glbl -env /glbl { 907643} virtual_000001
quietly WaveActivateNextPane {} 0
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/clock
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/reset
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/start
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/lfsr_seed
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/valid_seed
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/lfsr_polynomial
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/mac_source
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/mac_destination
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ip_source
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ip_destination
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/packet_length
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/timestamp_base
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/time_stamp_flag
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_full
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_data
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_val
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_sop
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_eop
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_mod
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/payload_type
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/payload_cycles
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/current_s
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/next_s
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/MAC
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/IP
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/EOH_SOF
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/HEADER
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/PAYLOAD
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/PAYLOAD_PKT
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/PAYLOAD_LAST
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/IDLE_VALUE
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/UPD_INFO
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ALL_ONE
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ALL_ZERO
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/PKT_COUNTER
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ID_COUNTER_H
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ID_COUNTER_L
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/SEED
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/RANDOM
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/start_lfsr
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/preset_lfsr
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/count
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_data_N
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_data_buffer
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_mod_reg
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_eop_reg
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/last_pkt
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/time_stamp
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/it_payload
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/it_mod
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ip_checksum
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/aux_checksum
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ip_message_length
add wave -noupdate -group GEN_0 /tb_4xgth/TESTER_0/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/udp_message_length
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/clock
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/reset
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/start
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/lfsr_seed
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/valid_seed
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/lfsr_polynomial
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/mac_source
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/mac_destination
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ip_source
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ip_destination
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/packet_length
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/timestamp_base
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/time_stamp_flag
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_full
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_data
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_val
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_sop
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_eop
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_mod
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/payload_type
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/payload_cycles
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/current_s
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/next_s
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/MAC
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/IP
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/EOH_SOF
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/HEADER
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/PAYLOAD
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/PAYLOAD_PKT
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/PAYLOAD_LAST
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/IDLE_VALUE
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/UPD_INFO
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ALL_ONE
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ALL_ZERO
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/PKT_COUNTER
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ID_COUNTER_H
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ID_COUNTER_L
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/SEED
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/RANDOM
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/start_lfsr
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/preset_lfsr
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/count
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_data_N
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_data_buffer
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_mod_reg
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/pkt_tx_eop_reg
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/last_pkt
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/time_stamp
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/it_payload
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/it_mod
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ip_checksum
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/aux_checksum
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/ip_message_length
add wave -noupdate -group GEN_1 /tb_4xgth/TESTER_1/TX_ARCH_INST/inst_pkt_creation_mngr/echo_gen_inst/udp_message_length
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/clk_312
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reset
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_seed
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_polynomial
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/valid_seed
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/timestamp_base
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/mac_source
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/mac_source_rx
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/mac_destination
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/ip_source
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/ip_destination
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/time_stamp_out
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/received_packet
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/end_latency
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/packets_lost
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/RESET_done
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_ren
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_avail
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_eop
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_sop
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_val
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_err
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_data
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_mod
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/payload_type
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/verify_system_rec
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reset_test
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_sequence_in
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_sequence_error_flag
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_sequence_error
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/count_error
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/IDLE_count
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/current_s
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/next_s
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_state
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/recovery_state
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_data_buffer
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_data_nbits
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_rx_data_N
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/pkt_sequence_error_flag_aux
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reg_mac_source
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reg_mac_destination
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reg_ip_source
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reg_ip_destination
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reg_ethernet_type
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reg_ip_protocol
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/reg_ip_message_length
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/ip_high
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/ip_pkt_type
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/udp_pkt_type
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/time_stamp_generator
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/time_stamp_receiver
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/time_stamp_ready
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/received_packet_wire
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/id_pkt_tester
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/id_sequence_counter
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/id_current_pkg_number
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lost_pkt_flag
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/not_lost_pkt_test
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lost_counter
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lost_pkt_tester
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/IDLE_count_reg
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/RANDOM
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_bert
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/start
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_start
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_start_delay
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_resync_ON
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_fsm_begin
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_test_begin
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_load_seed
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/delay_B0
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/delay_B1
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/delay_B2
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_resync_SIGNAL
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_resync_RANDOM
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/lfsr_counter
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/const_test_begin
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/bert_target_lfsr
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/bert_xor
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/bert_cycle_wrong
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/bert_n_flipped_b
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/bert_count_flip
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/bert_test_begin
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/ALL_ONE
add wave -noupdate -group REC_0 /tb_4xgth/TESTER_0/RX_ARCH_INST/inst_echo_receiver/ALL_ZERO
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/clk_312
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reset
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_seed
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_polynomial
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/valid_seed
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/timestamp_base
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/mac_source
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/mac_source_rx
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/mac_destination
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/ip_source
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/ip_destination
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/time_stamp_out
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/received_packet
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/end_latency
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/packets_lost
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/RESET_done
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_ren
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_avail
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_eop
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_sop
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_val
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_err
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_data
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_mod
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/payload_type
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/verify_system_rec
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reset_test
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_sequence_in
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_sequence_error_flag
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_sequence_error
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/count_error
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/IDLE_count
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/current_s
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/next_s
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_state
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/recovery_state
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_data_buffer
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_data_nbits
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_rx_data_N
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/pkt_sequence_error_flag_aux
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reg_mac_source
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reg_mac_destination
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reg_ip_source
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reg_ip_destination
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reg_ethernet_type
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reg_ip_protocol
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/reg_ip_message_length
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/ip_high
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/ip_pkt_type
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/udp_pkt_type
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/time_stamp_generator
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/time_stamp_receiver
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/time_stamp_ready
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/received_packet_wire
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/id_pkt_tester
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/id_sequence_counter
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/id_current_pkg_number
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lost_pkt_flag
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/not_lost_pkt_test
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lost_counter
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lost_pkt_tester
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/IDLE_count_reg
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/RANDOM
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_bert
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/start
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_start
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_start_delay
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_resync_ON
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_fsm_begin
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_test_begin
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_load_seed
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/delay_B0
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/delay_B1
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/delay_B2
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_resync_SIGNAL
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_resync_RANDOM
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/lfsr_counter
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/const_test_begin
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/bert_target_lfsr
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/bert_xor
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/bert_cycle_wrong
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/bert_n_flipped_b
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/bert_count_flip
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/bert_test_begin
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/ALL_ONE
add wave -noupdate -group REC_1 /tb_4xgth/TESTER_1/RX_ARCH_INST/inst_echo_receiver/ALL_ZERO
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{inicio do pkt no rx} {366601643200 ps} 1} {{Cursor 5} {342935 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 252
configure wave -valuecolwidth 279
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {52933245 ps} {53003514 ps}
bookmark add wave bookmark5 {{770754 ps} {811500 ps}} 13
bookmark add wave bookmark6 {{780000 ps} {800000 ps}} 8
bookmark add wave bookmark7 {{0 ps} {42010 ps}} 0
bookmark add wave bookmark8 {{201305 ps} {266263 ps}} 7
bookmark add wave bookmark9 {{728057 ps} {794311 ps}} 6
bookmark add wave bookmark10 {{1931987 ps} {1965959 ps}} 9
